# Generated by Django 3.2.8 on 2021-10-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_contactmessage_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slider/')),
                ('title', models.CharField(max_length=100)),
                ('offer', models.CharField(max_length=200)),
            ],
        ),
    ]
